development: &global_settings
  database: textual_development
  host: 127.0.0.1
  port: 27017

test:
  database: textual_test
  <<: *global_settings

production:
  host: hostname
  database: databasename
  username: username
  password: password
  <<: *global_settings