# if HTTPError fetching htts://rubygem.org https://github.com/rubygems/rubygems/issues/2253
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.2"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 6.0.3", ">= 6.0.3.4"

gem "mongo"
#mongoid mapper
gem "mongoid", "~> 7.2"

#gem 'active_model_serializers', '~> 0.8.3' # NOTE: not the 0.9
#gem "devise_token_auth"
gem "grape"
# RuboCop extension focused on enforcing Rails best practices and coding conventions.
gem "rubocop-rails", require: false

# Use Puma as the app server
gem "puma", "~> 4.1"
# Use SCSS for stylesheets
gem "sass-rails", ">= 6"
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem "webpacker", "~> 4.0"
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem "turbolinks", "~> 5"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder", "~> 2.7"
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem "bcrypt", "~> 3.1.7"
# allows the Cross-Origin Resource Sharing (CORS) in the API. CORS prevents API calls from unknown origins
gem "rack-cors", "~> 1.1", ">= 1.1.1"
#Json Web Token
gem "jwt"
gem "simple_command"
# Use Active Storage variant
# gem 'image_processing', '~> 1.2'
# https://github.com/mrrooijen/mongoid-paperclip
gem "mongoid-paperclip"
gem "bson_ext"
#https://medium.com/@dakota.lillie/uploading-files-using-carrierwave-in-rails-81ef54ebbcdb
gem "carrierwave-aws"
gem "carrierwave-mongoid", :require => "carrierwave/mongoid"
gem "carrierwave_direct"
gem "mini_magick"
gem "aws-sdk-rails"
#gem 'figaro'
#https://code.tutsplus.com/articles/uploading-with-rails-and-carrierwave--cms-28409
gem "fog-aws"
gem "excon"
gem "jquery-rails"
# temp work0around https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1
gem "mimemagic", github: "mimemagicrb/mimemagic", ref: "01f92d86d15d85cfd0f20dabd025dcbd36a8a60f"
# part of the AWS SDK for Ruby.
#gem "aws-sdk-s3"
# https://medium.com/@andrea.wayte/using-amazon-s3-to-store-images-for-react-on-rails-b1414ba2c0b2
gem "aws-sdk-ec2", "~> 1"

# allow us to stash credentials in a .env file and load them as environment variables while running a Rails server
# https://medium.com/@spikeburton/setting-up-file-storage-using-aws-s3-for-rails-and-react-c25cceac56d8
gem "dotenv-rails"
# https://www.rubydoc.info/gems/geocoder/1.1.8
gem "geocoder"
# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  # Testing framework
  gem "rspec-rails", "~> 4.0.2"
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem "web-console", ">= 3.3.0"
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem "capybara", ">= 2.15"
  gem "selenium-webdriver"
  # Easy installation and use of web drivers to run system tests with browsers
  gem "webdrivers"
  # A fixtures replacement with a more straightforward syntax
  gem "factory_bot_rails"
  # Provides RSpec with additional matchers
  gem "shoulda-matchers", "~> 4.0"
  #  A library for generating fake data
  gem "faker", git: "https://github.com/stympy/faker"
  # cleans our test database to ensure a clean state in each test suite
  gem "database_cleaner"
  # library provides a collection of RSpec-compatible matchers that help to test Mongoid documents .https://github.com/mongoid/mongoid-rspec
  gem "mongoid-rspec", :group => :test
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
