export const SUCCESS = "SUCCESS";

export const FAILURE = "FAILURE";

/**AUTHENTHICATE ACTIONS*/
export const RETRIEVE_TOKEN = "RETRIEVE_TOKEN";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGOUT = "LOGOUT";

/**INPUT ACTIONS*/
export const USER_INPUT_CHANGE = "USER_INPUT_CHANGE";

export const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT";

/**MAP ACTIONS*/
export const USER_ONLINE = "USER_ONLINE";

export const USER_OFFLINE = "USER_OFFLINE";

export const LOCATION_PERMISSION_SUCCESS = "LOCATION_PERMISSION_SUCCESS";