export const SUCCESS = "SUCCESS";

export const FAILURE = "FAILURE";

/**AUTHENTHICATE ACTIONS*/
export const API_CALL = "API_CALL";

export const RETRIEVE_TOKEN = "RETRIEVE_TOKEN";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGOUT = "LOGOUT";

export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";

/**INPUT ACTIONS*/
export const USER_INPUT_CHANGE = "USER_INPUT_CHANGE";

export const USER_INPUT_SUBMIT = "USER_INPUT_SUBMIT";

/**MAP ACTIONS*/
export const USER_ONLINE = "USER_ONLINE";

export const USER_OFFLINE = "USER_OFFLINE";

export const LOCATION_PERMISSION_SUCCESS = "LOCATION_PERMISSION_SUCCESS";

/**POST ACTIONS */
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";

export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";

export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";

export const POSTS_FETCH_ALL_SUCCESS = "POSTS_FETCH_ALL_SUCCESS";

export const POSTS_FETCH_ALL_ERROR = "POSTS_FETCH_ALL_ERROR";
